#!/bin/bash

update_home() {
	set -ue
	if [ -d "${HOME}/configs" ]; then
		(
		    cd "${HOME}/configs/"
		    git pull
		)
	else
		(
		    cd "${HOME}"
		    git clone git@github.com:DenKoren/configs.git || git clone https://github.com/DenKoren/configs.git
		    make --makefile "${HOME}/configs/dotfiles/Makefile" common
		)
	fi
}

sshome () {
	if [ "$#" -gt "0" ]; then
		(
		    declare -f update_home;
		    echo update_home
		) | ssh "${@}" 'sh -x'
	else
		update_home
	fi
}
