#!/bin/bash

update_home() {
	set -ue
	if [ -d "${HOME}/configs" ]; then
		(
		    command cd "${HOME}/configs/"
		    command git pull
		)
	else
		(
		    command cd "${HOME}"
		    command git clone https://github.com/DenKoren/configs.git
		    command make --makefile "${HOME}/configs/dotfiles/Makefile" common
		)
	fi
}

sshome () {
	if [ "$#" -gt "0" ]; then
		(
		    declare -f update_home;
		    echo update_home
		) | ssh "${@}" 'sh -x'
	else
		update_home
	fi
}

complete -F _known_hosts sshome
