#!/bin/bash

sswhile () {
	local _ssh_host
	local _ssh_

	_ssh_host="$1"
    shift 1
	_ssh_options="ConnectTimeout=1"
	_ssh_="ssh -o ${_ssh_options}"

	printf "Waiting for ssh availability of '${_ssh_host}'...\n"

	while ! ${_ssh_} "${_ssh_host}" "${@}"; do
		true
	done
}
