# vim: set noexpandtab:

function mi.pl.events-generated --description 'Get flat list of events generated by transactions'
	set --local eventID $argv[1]

	if [ -z $eventID ]
		jq --compact-output \
			'select(.changesSummary.EventsGenerated) |
			{
				"txID": .txID, "events": (
					.changesSummary.EventsGenerated |
					reduce .[] as $x ({}; . * $x)
				)
			}'
	else
		jq --compact-output \
			'select(.changesSummary.EventsGenerated) |
			{
				"txID": .txID, "events": (
					.changesSummary.EventsGenerated |
					reduce .[] as $x ({}; . * $x)
				)
			}' |
			jq --compact-output \
				--arg eID $eventID \
				'select(.events[$eID])'
	end
end

