# vim: set noexpandtab:

function mi.pl.events-generated --description 'Get flat list of events generated by transactions'
	jq \
		'select(.changesSummary.EventsGenerated) |
		{
			"txID": .txID, "events": (
				.changesSummary.EventsGenerated |
				reduce .[] as $x ({}; . * $x)
			)
		}'
end

