#!/usr/bin/env ansible-playbook --ask-become-pass
# vim: set nospell shiftwidth=2:

- hosts: localhost

  vars:

    homebrew_cask_apps:

      - arduino
      - repetier-host
      - ultimaker-cura

  roles:
    - geerlingguy.mac.homebrew
