#!/usr/bin/env ansible-playbook --ask-become-pass
# vim: set nospell shiftwidth=2:

- hosts: localhost

  vars:

    homebrew_installed_packages:
      - go
      - protobuf
      - homebrew/php/php71

    homebrew_cask_apps:
      - phpstorm
      - goland
      - sequel-pro
      - java
      - mattermost

  roles:
    - geerlingguy.mac.homebrew
