#!/usr/bin/env ansible-playbook --ask-become-pass
# vim: set nospell shiftwidth=2:

- hosts: localhost

  vars:

    mas_installed_apps:
      # Apple software
      - { id: 409201541, name: "Pages" }
      - { id: 409203825, name: "Numbers" }
      - { id: 497799835, name: "XCode" }

      # Utils and productivity
      - { id: 919269455, name: "Stufflt Expander" }
      - { id: 441258766, name: "Magnet" }

      # Clouds
      - { id: 560459030, name: "Yandex.Disk" }
      - { id: 1274495053, name: "Microsoft To Do" }

    homebrew_installed_packages:
      - bash-completion
      - bash-git-prompt
      - git
      - git-lfs
      - jq
      - yq
      - bat
      - fish
      - wget
      - p7zip
      - vim

    homebrew_cask_apps:

      # Browsers and network utilities
      - google-chrome
      - firefox
      - transmission
      - tor-browser

      # Messengers
      - skype
      - telegram
      - whatsapp

      # Others
      - vlc
      - alfred
      - iterm2
      - keepassx
      - dropbox
      - yandex-disk
      - virtualbox
      - docker
      - webcatalog

  roles:
    - geerlingguy.homebrew
    - geerlingguy.mas
