#!/usr/bin/env ansible-playbook --ask-become-pass
# vim: set nospell shiftwidth=2:

- hosts: localhost

  vars:

    mas_installed_apps:
      # Apple software
      - { id: 409201541, name: "Pages" }
      - { id: 409203825, name: "Numbers" }
      #- { id: 497799835, name: "XCode" }
      - { id: 1451685025, name: "WireGuard" }

      # Utils and productivity
      - { id: 919269455, name: "Stufflt Expander" }
      - { id: 441258766, name: "Magnet" }

      # Clouds
      - { id: 1274495053, name: "Microsoft To Do" }

    homebrew_installed_packages:
      - bash-completion
      - bash-git-prompt
      - git
      - git-lfs
      - jq
      - yq
      - pv
      - bat
      - fish
      - wget
      - p7zip
      - vim
      - wireguard-tools
      - ipcalc

    homebrew_cask_apps:

      # Browsers and network utilities
      - google-chrome
      - firefox
      - microsoft-edge
      - transmission
      - tor-browser
      - webcatalog

      # Messengers
      - telegram
      - whatsapp
      - skype
      - zoom

      # Others
      - vlc
      - alfred
      - iterm2
      - keepassx
      - dropbox
      - yandex-disk

      # Development
      - jetbrains-toolbox
      - docker
      - virtualbox

  roles:
    - geerlingguy.homebrew
    - geerlingguy.mas
