#!/usr/bin/env ansible-playbook --ask-become-pass
# vim: set nospell shiftwidth=2:

- hosts: localhost

  vars:

    homebrew_installed_packages:
      - go
      - protobuf
      - awscli
      - aws-cdk

    homebrew_cask_apps:
      - aws-vault
      - phpstorm
      - goland
      - intellij-idea
      - pycharm
      - sequel-pro
      - temurin11

  roles:
    - geerlingguy.homebrew
