#!/usr/bin/env ansible-playbook --ask-become-pass
# vim: set nospell shiftwidth=2:

- hosts: localhost

  vars:

    homebrew_installed_packages:
      - go
      - golangci-lint
      - protobuf
      - awscli
      - aws-cdk

      # Casks
      - aws-vault
      - visual-studio-code
      #- phpstorm
      #- goland
      #- intellij-idea
      #- pycharm
      - sequel-pro
      - temurin11
      - bloomrpc

  roles:
    - geerlingguy.mac.homebrew
