#!/usr/bin/env ansible-playbook --ask-become-pass
# vim: set nospell shiftwidth=2:

- hosts: localhost

  vars:

    homebrew_installed_packages:
      - go@1.12
      - protobuf
      - bats-core
      - npm
      - shellcheck
      - kubectl
      - kubectx
      - python3
      - derailed/k9s/k9s
      - stern
      - golangci/tap/golangci-lint

    homebrew_cask_apps:
      - goland
      - sequel-pro
      - java
      - slack
      - bloomrpc
      - tunnelblick

  roles:
    - geerlingguy.mac.homebrew
