#!/usr/bin/env ansible-playbook --ask-become-pass
# vim: set nospell shiftwidth=2:

- hosts: localhost

  vars:

    homebrew_installed_packages:
      - go
      - protobuf
      - python3
      - golangci/tap/golangci-lint

    homebrew_cask_apps:
      - goland
      - pycharm
      - java
      - bloomrpc
      - zoomus
      - osxfuse

  roles:
    - geerlingguy.mac.homebrew
